from typing import Any, Dict, List, Optional
from app.adapters.base import BaseProviderAdapter
from app.adapters.openai import GenericOpenAIAdapter
from app.adapters.google import GoogleAIStudioAdapter
from app.adapters.anthropic import AnthropicAdapter

PROVIDER_PRESETS: List[Dict[str, Any]] = [
    {
        "name": "Google AI Studio / Gemini",
        "slug": "google",
        "adapter_type": "google",
        "base_url": "https://generativelanguage.googleapis.com",
        "models_endpoint": "/v1beta/models",
        "chat_endpoint": "/v1beta/openai/chat/completions",
        "responses_endpoint": "/v1beta/openai/chat/completions",
        "auth_type": "bearer",
        "auth_header": "Authorization",
        "extra_headers": {},
        "configuration": {"default_models": ["gemini-2.5-flash", "gemini-2.5-pro", "gemini-2.0-flash"]},
    },
    {
        "name": "OpenAI",
        "slug": "openai",
        "adapter_type": "openai",
        "base_url": "https://api.openai.com/v1",
        "models_endpoint": "/models",
        "chat_endpoint": "/chat/completions",
        "responses_endpoint": "/responses",
        "auth_type": "bearer",
        "auth_header": "Authorization",
        "extra_headers": {},
        "configuration": {},
    },
    {
        "name": "Anthropic",
        "slug": "anthropic",
        "adapter_type": "anthropic",
        "base_url": "https://api.anthropic.com",
        "models_endpoint": "/v1/models",
        "chat_endpoint": "/v1/messages",
        "responses_endpoint": None,
        "auth_type": "x-api-key",
        "auth_header": "x-api-key",
        "extra_headers": {"anthropic-version": "2023-06-01"},
        "configuration": {},
    },
    {
        "name": "OpenRouter",
        "slug": "openrouter",
        "adapter_type": "openrouter",
        "base_url": "https://openrouter.ai/api/v1",
        "models_endpoint": "/models",
        "chat_endpoint": "/chat/completions",
        "responses_endpoint": None,
        "auth_type": "bearer",
        "auth_header": "Authorization",
        "extra_headers": {"HTTP-Referer": "https://myairouter.local", "X-Title": "MyAIrouter"},
        "configuration": {},
    },
    {
        "name": "Groq",
        "slug": "groq",
        "adapter_type": "groq",
        "base_url": "https://api.groq.com/openai/v1",
        "models_endpoint": "/models",
        "chat_endpoint": "/chat/completions",
        "responses_endpoint": None,
        "auth_type": "bearer",
        "auth_header": "Authorization",
        "extra_headers": {},
        "configuration": {},
    },
    {
        "name": "DeepSeek",
        "slug": "deepseek",
        "adapter_type": "deepseek",
        "base_url": "https://api.deepseek.com",
        "models_endpoint": "/models",
        "chat_endpoint": "/chat/completions",
        "responses_endpoint": None,
        "auth_type": "bearer",
        "auth_header": "Authorization",
        "extra_headers": {},
        "configuration": {},
    },
    {
        "name": "Mistral AI",
        "slug": "mistral",
        "adapter_type": "mistral",
        "base_url": "https://api.mistral.ai/v1",
        "models_endpoint": "/models",
        "chat_endpoint": "/chat/completions",
        "responses_endpoint": None,
        "auth_type": "bearer",
        "auth_header": "Authorization",
        "extra_headers": {},
        "configuration": {},
    },
    {
        "name": "Together AI",
        "slug": "together",
        "adapter_type": "together",
        "base_url": "https://api.together.xyz/v1",
        "models_endpoint": "/models",
        "chat_endpoint": "/chat/completions",
        "responses_endpoint": None,
        "auth_type": "bearer",
        "auth_header": "Authorization",
        "extra_headers": {},
        "configuration": {},
    },
    {
        "name": "xAI",
        "slug": "xai",
        "adapter_type": "xai",
        "base_url": "https://api.x.ai/v1",
        "models_endpoint": "/models",
        "chat_endpoint": "/chat/completions",
        "responses_endpoint": None,
        "auth_type": "bearer",
        "auth_header": "Authorization",
        "extra_headers": {},
        "configuration": {},
    },
    {
        "name": "Fireworks AI",
        "slug": "fireworks",
        "adapter_type": "fireworks",
        "base_url": "https://api.fireworks.ai/inference/v1",
        "models_endpoint": "/models",
        "chat_endpoint": "/chat/completions",
        "responses_endpoint": None,
        "auth_type": "bearer",
        "auth_header": "Authorization",
        "extra_headers": {},
        "configuration": {},
    },
    {
        "name": "Custom OpenAI Compatible",
        "slug": "custom-openai",
        "adapter_type": "generic_openai",
        "base_url": "http://localhost:8000/v1",
        "models_endpoint": "/models",
        "chat_endpoint": "/chat/completions",
        "responses_endpoint": None,
        "auth_type": "bearer",
        "auth_header": "Authorization",
        "extra_headers": {},
        "configuration": {},
    },
]

_adapters: Dict[str, BaseProviderAdapter] = {
    "google": GoogleAIStudioAdapter(),
    "anthropic": AnthropicAdapter(),
    "openai": GenericOpenAIAdapter(),
    "openrouter": GenericOpenAIAdapter(),
    "groq": GenericOpenAIAdapter(),
    "deepseek": GenericOpenAIAdapter(),
    "mistral": GenericOpenAIAdapter(),
    "together": GenericOpenAIAdapter(),
    "xai": GenericOpenAIAdapter(),
    "fireworks": GenericOpenAIAdapter(),
    "generic_openai": GenericOpenAIAdapter(),
}

def get_adapter(adapter_type: str) -> BaseProviderAdapter:
    clean_type = adapter_type.lower().strip()
    return _adapters.get(clean_type, _adapters["generic_openai"])
